indexing-settings:
  sites:
    - url: https://thepike.ru/
      name: The Pike
    - url: https://sergeybezrukov.ru/
      name: Bezrukov
server:
  port: 8080
spring:
#  profiles:
#    default: "dev"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: MyNewPass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        jdbc:
          batch_size: 50000
    hibernate:
      ddl-auto: update
    show-sql: false
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate:
      SQL: ERROR
#      orm.jdbc.bind: TRACE
  file: hibernate.log

